Repository eradiate/eradiate, pull requests merged in 2021-03, with the labels that each got.

#42 Added thermoprops utilities for clouds
  eradiate/thermoprops/tests/test_thermoprops_util.py
  eradiate/thermoprops/util.py
  requirements/environment-linux-64.lock
  requirements/environment-osx-64.lock
  requirements/environment.yml
  setup.cfg
Labels: enhancement 🦾

#47 Documented models for atmospheric scattering and absorption
  docs/references.bib
  docs/rst/user_guide/atmosphere/absorption.rst
  docs/rst/user_guide/atmosphere/index.rst
  docs/rst/user_guide/atmosphere/scattering.rst
  docs/rst/user_guide/intro.rst
  eradiate/radprops/rayleigh.py
Labels: documentation 📚

#53 presolver: Raise a user friendly ValueError when the ERADIATE_DIR env var is not set correctly
  eradiate/_presolver.py
Labels: enhancement 🦾, good first issue 👋
