Repository eradiate/eradiate, pull requests merged in 2021-02, with the labels that each got.

#33 Refactored compute_sigma_a
  docs/rst/getting_started/install.rst
  docs/rst/user_guide/molecular_absorption_datasets.rst
  eradiate/data/absorption_spectra.py
  eradiate/radprops/absorption.py
  eradiate/radprops/rad_profile.py
  eradiate/radprops/tests/test_absorption.py
Labels: bug 🐛, enhancement 🦾

#32 Change tutorial engine: switch to sphinx-gallery
  .gitignore
  docs/Makefile
  docs/_ext/ertdocs.py
  docs/conf.py
  docs/examples/tutorials/01_quick_overview.py
  docs/examples/tutorials/01_quick_overview_config.yml
  docs/examples/tutorials/README.txt
  docs/examples/tutorials/data/01_xarray.py
  docs/examples/tutorials/data/02_custom_solar_irradiance.py
  docs/examples/tutorials/data/02_custom_solar_irradiance_data.csv
  docs/examples/tutorials/data/README.txt
  docs/examples/tutorials/solver_onedim/01_solver_onedim.py
  docs/examples/tutorials/solver_onedim/01_solver_onedim_config.yml
  docs/examples/tutorials/solver_onedim/02_heterogeneous_atmospheres.py
  docs/examples/tutorials/solver_onedim/README.txt
  docs/examples/tutorials/solver_rami/01_solver_rami.py
  docs/examples/tutorials/solver_rami/README.txt
  docs/fig/solid_2017.png
  docs/fig/thuillier_2003.png
  docs/index.rst
  docs/notebooks/tutorials/onedim_solver_app/config.yml
  docs/notebooks/tutorials/onedim_solver_app/heterogeneous_atmospheres.ipynb
  docs/notebooks/tutorials/onedim_solver_app/onedim_solver_app.ipynb
  docs/notebooks/tutorials/quick_overview/config.yml
  docs/notebooks/tutorials/quick_overview/quick_overview.ipynb
  docs/notebooks/tutorials/rami_solver_app/rami_solver_app.ipynb
  docs/notebooks/tutorials/solar_irradiance_spectra/add_your_own_solar_irradiance_spectrum_dataset.ipynb
  docs/notebooks/tutorials/solar_irradiance_spectra/my_data.csv
  docs/notebooks/tutorials/xarray/xarray.ipynb
  docs/rst/developer_guide/adding_tutorials.rst
  docs/rst/developer_guide/intro.rst
  docs/rst/developer_guide/tutorials.rst
  docs/rst/user_guide/data_guide.rst
  docs/rst/user_guide/intro.rst
  docs/rst/user_guide/onedim_solver_app.rst
  docs/rst/user_guide/solar_irradiance_spectra.rst
  requirements/dev.txt
  requirements/docs.in
  requirements/docs.txt
  requirements/environment-linux-64.lock
  requirements/environment-osx-64.lock
  requirements/environment.yml
  setup.cfg
Labels: documentation 📚, infrastructure 🏗️

#34 Attribute docs
  docs/rst/developer_guide/documentation.rst
  docs/rst/developer_guide/intro.rst
  docs/rst/developer_guide/tutorials.rst
  eradiate/radprops/rad_profile.py
  eradiate/scenes/atmosphere/base.py
  eradiate/scenes/atmosphere/heterogeneous.py
  eradiate/scenes/atmosphere/homogeneous.py
  eradiate/scenes/biosphere.py
  eradiate/scenes/core.py
  eradiate/scenes/illumination.py
  eradiate/scenes/integrators.py
  eradiate/scenes/measure.py
  eradiate/scenes/spectra.py
  eradiate/scenes/surface.py
  eradiate/solvers/onedim/app.py
  eradiate/solvers/onedim/runner.py
  eradiate/solvers/rami/app.py
  eradiate/util/attrs.py
  eradiate/util/xarray.py
Labels: documentation 📚, infrastructure 🏗️

#39 Added missing import eradiate.data
  eradiate/radprops/rad_profile.py
Labels: bug 🐛

#37 Updated docs of US76ApproxRadProfile
  eradiate/radprops/rad_profile.py
Labels: documentation 📚

#26 Resolve "default max value for heterogeneous atmosphere automatic width"
  eradiate/scenes/atmosphere/heterogeneous.py
Labels: enhancement 🦾

#45 Updated date in copyright text
  docs/conf.py
Labels: documentation 📚
