Repository eradiate/eradiate, pull requests merged in 2021-08, with the labels that each got.

#110 RadProfile mode safeguards
  eradiate/radprops/rad_profile.py
Labels: bug 🐛

#111 Make ParticleLayer inherit Atmosphere
  docs/_ext/ertdocs.py
  docs/generate_rst_api.py
  docs/rst/reference/generated/factory/eradiate.scenes.atmosphere._particle_dist.particle_distribution_factory.rst
  docs/rst/reference/radprops.rst
  docs/rst/reference/scenes.rst
  eradiate/radprops/__init__.py
  eradiate/radprops/particles.py
  eradiate/radprops/rad_profile.py
  eradiate/scenes/atmosphere/__init__.py
  eradiate/scenes/atmosphere/_core.py
  eradiate/scenes/atmosphere/_heterogeneous.py
  eradiate/scenes/atmosphere/_particle_dist.py
  eradiate/scenes/atmosphere/_particles.py
  eradiate/scenes/atmosphere/tests/test_heterogeneous.py
  eradiate/scenes/atmosphere/tests/test_particle_dist.py
  eradiate/scenes/atmosphere/tests/test_particles.py
Labels: enhancement 🦾

#112 Refactoring of rad_profile module
  eradiate/radprops/rad_profile.py
  eradiate/radprops/tests/test_rad_profile.py
  eradiate/scenes/atmosphere/_core.py
  eradiate/scenes/atmosphere/_heterogeneous.py
  eradiate/scenes/atmosphere/tests/test_heterogeneous.py
  eradiate/thermoprops/afgl1986.py
  eradiate/thermoprops/tests/test_afgl1986.py
Labels: enhancement 🦾

#114 Fix true_divide warning
  eradiate/tests/system/test_albedo.py
Labels: enhancement 🦾

#102 New heterogeneous atmosphere design
  docs/rst/reference/scenes.rst
  eradiate/contexts.py
  eradiate/scenes/atmosphere/__init__.py
  eradiate/scenes/atmosphere/_core.py
  eradiate/scenes/atmosphere/_heterogeneous.py
  eradiate/scenes/atmosphere/_heterogeneous_new.py
  eradiate/scenes/atmosphere/_molecules.py
  eradiate/scenes/atmosphere/_particles.py
  eradiate/scenes/atmosphere/tests/test_atmosphere_core.py
  eradiate/scenes/atmosphere/tests/test_heterogeneous_new.py
  eradiate/scenes/atmosphere/tests/test_molecules.py
  eradiate/scenes/atmosphere/tests/test_particles.py
  eradiate/scenes/surface/_core.py
  eradiate/scenes/surface/tests/test_surface_core.py
  eradiate/solvers/onedim/_scene.py
  eradiate/solvers/rami/_scene.py
  eradiate/solvers/tests/test_rami.py
  eradiate/thermoprops/util.py
Labels: enhancement 🦾, infrastructure 🏗️
