Repository eradiate/eradiate, pull requests merged in 2021-05, with the labels that each got.

#68 77 absorption switch
  eradiate/radprops/rad_profile.py
  eradiate/radprops/tests/test_rad_profile.py
Labels: enhancement 🦾

#75 Fixed eradiate.thermoprops.interpolate
  eradiate/thermoprops/util.py
Labels: bug 🐛

#77 Fix default levels for standard atmospheric profiles
  eradiate/radprops/rad_profile.py
  eradiate/scenes/atmosphere/tests/test_heterogeneous.py
Labels: bug 🐛

#79 Changed heterogeneous atmosphere default profile
  eradiate/scenes/atmosphere/_heterogeneous.py
  eradiate/scenes/atmosphere/tests/test_heterogeneous.py
Labels: enhancement 🦾

#80 Docker: Fix eradiate installation and ERADIATE_DIR variable setup
  Dockerfile
Labels: bug 🐛, infrastructure 🏗️

#81 Generalised use of to_quantity()
  docs/rst/reference/core.rst
  eradiate/_units.py
  eradiate/plot.py
  eradiate/radprops/absorption.py
  eradiate/radprops/rad_profile.py
  eradiate/scenes/spectra/_solar_irradiance.py
  eradiate/thermoprops/util.py
Labels: enhancement 🦾

#84 Fixed apply_srf to compute a weighted mean instead of a weighted sum
  eradiate/solvers/core/_postprocess.py
Labels: enhancement 🦾

#85 Updated AFGL1986RadProfile docstrings examples
  eradiate/radprops/rad_profile.py
Labels: documentation 📚
