Repository eradiate/eradiate, pull requests merged in 2022-04, with the labels that each got.

#202 Make `config.progress` an `IntEnum`
  CHANGELOG.md
  docs/rst/reference_api/config.rst
  src/eradiate/_config.py
  src/eradiate/experiments/_core.py
  src/eradiate/kernel/logging.py
  tests/02_eradiate/01_unit/test_config.py
Labels: enhancement 🦾, refactoring 🚧

#185 CKD dataset update
  CHANGELOG.md
  src/eradiate/radprops/_afgl1986.py
  src/eradiate/radprops/_util_ckd.py
  src/eradiate/thermoprops/afgl_1986.py
  src/eradiate/thermoprops/util.py
  tests/02_eradiate/01_unit/radprops/test_afgl_1986.py
  tests/02_eradiate/01_unit/thermoprops/test_afgl1986.py
  tests/02_eradiate/01_unit/thermoprops/test_util.py
Labels: enhancement 🦾

#207 Tests: Improve regression testing framework
  CHANGELOG.md
  src/eradiate/test_tools/regression.py
  tests/02_eradiate/01_unit/test_tools/test_regression.py
  tests/02_eradiate/03_regression/atmospheres/test_rpv_afgl1986.py
  tests/02_eradiate/03_regression/atmospheres/test_rpv_afgl1986_continental.py
  tests/02_eradiate/03_regression/romc/test_het01.py
  tests/02_eradiate/03_regression/romc/test_het04.py
  tests/02_eradiate/03_regression/romc/test_het06.py
Labels: enhancement 🦾, ⚗️ testing

#208 CLI: Add registry content display feature to eradiate data info
  CHANGELOG.md
  src/eradiate/cli.py
Labels: enhancement 🦾, ⚗️ testing

#214 MeasureSpectralConfig: use Sentinel-2A/B2 SRF by default in CKD mode
  CHANGELOG.md
  src/eradiate/scenes/measure/_core.py
Labels: enhancement 🦾

#217 Added uninstall instructions
  CHANGELOG.md
  docs/rst/getting_started/install.rst
Labels: documentation 📚
